// Props
// style
// disabled
// maximumValue
// minimumTrackTintColor
// minimumValue
// onSlidingComplete
// onValueChange
// step
// maximumTrackTintColor
// testID
// value
// thumbTintColor
// maximumTrackImage
// minimumTrackImage
// thumbImage
// trackImage
